/* Materials from the HPA 3D printing material guide. Values are typical
   published figures for each family, not a single manufacturer's datasheet;
   real spools vary. Two fields are blank where the source had no figure:
   impact strength for the nylons and the high performance materials, and
   the overview text for the carbon filled and high performance sets.

   Three materials were corrected against published datasheets. PEI is
   amorphous and has no melting point, so the source's 220 degrees was the
   Vicat softening figure; its glass transition is 215 not 200 and its heat
   deflection 210 not 175. PEEK's glass transition is 143 not 150, melting
   343 not 340, heat deflection 152 not 140. PEKK as sold for filament is
   the amorphous A grade: glass transition 159, melting 308, heat deflection
   154. */

export const MATERIALS = [
  {"name": "PLA", "family": "Standard", "summary": "Inexpensive, easy", "overview": "PLA is generally considered the cheapest and easiest material to print. It's the go-to for prototypes and parts that don't have specific requirements. It's relatively brittle but quite strong and stiff", "tensileStrength": 50.0, "tensileModulus": 2700.0, "bendingStrength": 75.0, "bendingModulus": 2750.0, "impactStrength": 26.6, "elongation": 15.0, "glassTransition": 60.0, "meltingPoint": 150.0, "hdt": 57.0, "drying": "Optional", "desiccant": "Ideally", "nozzle": "190-230", "bed": "55-65", "speed": "<300", "fan": "50-100%", "enclosure": "Not Required"},
  {"name": "ABS", "family": "Standard", "summary": "Impact Resistant, durable", "overview": "A Step up in toughness compared to PLA but not quite as strong or stiff. Used for low cost parts that could be subject to impact or more abusive environments. Still relatively cheap before making the move to PA/Nylon.", "tensileStrength": 40.0, "tensileModulus": 1800.0, "bendingStrength": 62.0, "bendingModulus": 1880.0, "impactStrength": 39.3, "elongation": 15.0, "glassTransition": 105.0, "meltingPoint": 200.0, "hdt": 87.0, "drying": "Optional", "desiccant": "Ideally", "nozzle": "240-280", "bed": "90-100", "speed": "<300", "fan": "0-80%", "enclosure": "Recommended"},
  {"name": "ASA", "family": "Standard", "summary": "Impact resistant, UV Resistant", "overview": "Similar mechanical properties to ABS with good toughness, but a step up in heat resistance. Used for low cost parts that will be exposed to the elements.", "tensileStrength": 43.0, "tensileModulus": 2000.0, "bendingStrength": 65.0, "bendingModulus": 1920.0, "impactStrength": 41.0, "elongation": 8.0, "glassTransition": 105.0, "meltingPoint": 210.0, "hdt": 100.0, "drying": "Optional", "desiccant": "Ideally", "nozzle": "240-280", "bed": "90-100", "speed": "<300", "fan": "0-80%", "enclosure": "Recommended"},
  {"name": "PETG", "family": "Standard", "summary": "Chemical Resistant", "overview": "The toughest of the standard thermoplastic filaments, while not being particularly strong or stiff or heat resistance. Good for parts subject to impact without heat exposure", "tensileStrength": 50.0, "tensileModulus": 2500.0, "bendingStrength": 65.0, "bendingModulus": 2500.0, "impactStrength": 52.7, "elongation": 5.0, "glassTransition": 85.0, "meltingPoint": 200.0, "hdt": 69.0, "drying": "Optional", "desiccant": "Ideally", "nozzle": "240-270", "bed": "60-80", "speed": "<200", "fan": "0-60%", "enclosure": "Not Required"},
  {"name": "PC", "family": "Engineering", "summary": "Impact resistant, heat resistant", "overview": "A significant step up in strength and heat resistance, while not being quite as stiff as PLA. Used for parts thats require more strength and could be exposed to elevated temperature like in an engine bay but not too close to heat sources", "tensileStrength": 60.0, "tensileModulus": 2100.0, "bendingStrength": 90.0, "bendingModulus": 2310.0, "impactStrength": 34.8, "elongation": 10.0, "glassTransition": 150.0, "meltingPoint": 250.0, "hdt": 117.0, "drying": "Required", "desiccant": "Required", "nozzle": "260-290", "bed": "30-45", "speed": "<300", "fan": "0-60%", "enclosure": "Recommended"},
  {"name": "PA6", "family": "Nylon", "summary": "Impact Resistant, Durable, Heat Resistant", "overview": "Relatively strong & very tough, relatively cheap. Nylon offers a good step up in temperature resistance over our standard filaments", "tensileStrength": 68.0, "tensileModulus": 3500.0, "bendingStrength": 67.0, "bendingModulus": 3000.0, "impactStrength": null, "elongation": 4.0, "glassTransition": 65.0, "meltingPoint": 220.0, "hdt": 150.0, "drying": "Required", "desiccant": "Required", "nozzle": "250-280", "bed": "50-70", "speed": "<100", "fan": "0-40%", "enclosure": "Recommended"},
  {"name": "PA66", "family": "Nylon", "summary": "Heat resistance, Durable, Strong", "overview": "Better mechanical properties and heat resistance than PA6, but also more expensive", "tensileStrength": 75.0, "tensileModulus": 2800.0, "bendingStrength": 100.0, "bendingModulus": 2800.0, "impactStrength": null, "elongation": 20.0, "glassTransition": 75.0, "meltingPoint": 250.0, "hdt": 215.0, "drying": "Required", "desiccant": "Required", "nozzle": "250-280", "bed": "50-70", "speed": "<100", "fan": "0-40%", "enclosure": "Recommended"},
  {"name": "PA11", "family": "Nylon", "summary": "Heat resistant, Durable, flexible", "overview": "High temperature resistance while being Ductile and Flexible. Good for parts with thin wall and flexible functions like hinges", "tensileStrength": 49.0, "tensileModulus": 1500.0, "bendingStrength": 56.0, "bendingModulus": 1400.0, "impactStrength": null, "elongation": 30.0, "glassTransition": 50.0, "meltingPoint": 200.0, "hdt": 180.0, "drying": "Required", "desiccant": "Required", "nozzle": "250-280", "bed": "50-70", "speed": "<100", "fan": "0-40%", "enclosure": "Recommended"},
  {"name": "PA12", "family": "Nylon", "summary": "Heat resistant, Durable", "overview": "Very durable and relatively stiff. PA12 works well for Jigs, fixtures and tooling", "tensileStrength": 50.0, "tensileModulus": 1700.0, "bendingStrength": 55.0, "bendingModulus": 1800.0, "impactStrength": null, "elongation": 20.0, "glassTransition": 50.0, "meltingPoint": 190.0, "hdt": 175.0, "drying": "Required", "desiccant": "Required", "nozzle": "250-280", "bed": "50-70", "speed": "<100", "fan": "0-40%", "enclosure": "Recommended"},
  {"name": "PLA-CF", "family": "Carbon filled", "summary": "Strong, Stiff", "overview": null, "tensileStrength": 50.0, "tensileModulus": 4800.0, "bendingStrength": 89.0, "bendingModulus": 5000.0, "impactStrength": 23.2, "elongation": 2.0, "glassTransition": 60.0, "meltingPoint": 180.0, "hdt": 55.0, "drying": "Optional", "desiccant": "Required", "nozzle": "210-240", "bed": "45-65", "speed": "<250", "fan": "50-100%", "enclosure": "Not Required"},
  {"name": "PETG-CF", "family": "Carbon filled", "summary": "Chemically Resistant, durable, stiff", "overview": null, "tensileStrength": 55.0, "tensileModulus": 5000.0, "bendingStrength": 70.0, "bendingModulus": 5500.0, "impactStrength": 41.2, "elongation": 3.0, "glassTransition": 75.0, "meltingPoint": 220.0, "hdt": 74.0, "drying": "Optional", "desiccant": "Required", "nozzle": "240-270", "bed": "60-80", "speed": "<200", "fan": "0-40%", "enclosure": "Not Required"},
  {"name": "PET-CF", "family": "Carbon filled", "summary": "Heat resistant, stiff, strong", "overview": null, "tensileStrength": 100.0, "tensileModulus": 5000.0, "bendingStrength": 131.0, "bendingModulus": 5320.0, "impactStrength": 36.0, "elongation": 4.0, "glassTransition": 80.0, "meltingPoint": 250.0, "hdt": 205.0, "drying": "Required", "desiccant": "Required", "nozzle": "260-300", "bed": "70-100", "speed": "<100", "fan": "0-40%", "enclosure": "Not Required"},
  {"name": "PAHT-CF", "family": "Carbon filled", "summary": "Heat resistant, durable", "overview": null, "tensileStrength": 90.0, "tensileModulus": 4000.0, "bendingStrength": 125.0, "bendingModulus": 4230.0, "impactStrength": 57.5, "elongation": 8.0, "glassTransition": 70.0, "meltingPoint": 225.0, "hdt": 194.0, "drying": "Required", "desiccant": "Required", "nozzle": "260-300", "bed": "100-120", "speed": "<100", "fan": "0-40%", "enclosure": "Recommended"},
  {"name": "PA6-CF", "family": "Carbon filled", "summary": "Heat resistant, durable, Strong", "overview": null, "tensileStrength": 120.0, "tensileModulus": 5000.0, "bendingStrength": 151.0, "bendingModulus": 5460.0, "impactStrength": 40.3, "elongation": 2.0, "glassTransition": 80.0, "meltingPoint": 220.0, "hdt": 184.0, "drying": "Required", "desiccant": "Required", "nozzle": "260-300", "bed": "100-120", "speed": "<100", "fan": "0-40%", "enclosure": "Recommended"},
  {"name": "TPU", "family": "Flexible", "summary": "Tough, Impact resistant, durable", "overview": "Durable & Dense, Stiffer, Stronger, Tougher", "tensileStrength": 50.0, "tensileModulus": 26.0, "bendingStrength": 60.0, "bendingModulus": 80.0, "impactStrength": 125.2, "elongation": 300.0, "glassTransition": 110.0, "meltingPoint": 180.0, "hdt": 50.0, "drying": "Required", "desiccant": "Required", "nozzle": "220-240", "bed": "30-45", "speed": "<80", "fan": "50-100%", "enclosure": "Not Required"},
  {"name": "TPE/TPR", "family": "Flexible", "summary": "Flexible, Impact resistant, durable", "overview": "Lighter & More Flexible, not as durable", "tensileStrength": 10.0, "tensileModulus": 50.0, "bendingStrength": 20.0, "bendingModulus": 60.0, "impactStrength": null, "elongation": 400.0, "glassTransition": 110.0, "meltingPoint": 180.0, "hdt": 60.0, "drying": "Required", "desiccant": "Required", "nozzle": "210-260", "bed": "30-45", "speed": "<80", "fan": "0-30%", "enclosure": "Not Required"},
  {"name": "PEEK", "family": "High performance", "summary": "Chemically reistant, Heat resistant, Impact Resistant, Fire Resistant", "overview": null, "tensileStrength": 100.0, "tensileModulus": 3700.0, "bendingStrength": 130.0, "bendingModulus": 3000.0, "impactStrength": null, "elongation": 30.0, "glassTransition": 143, "meltingPoint": 343, "hdt": 152, "drying": "Required", "desiccant": "Required", "nozzle": "360-400", "bed": "120-160", "speed": "<50", "fan": "0-25%", "enclosure": "Required"},
  {"name": "PEKK", "family": "High performance", "summary": "Chemically reistant, Heat resistant, Impact Resistant, Fire Resistant", "overview": null, "tensileStrength": 95.0, "tensileModulus": 3500.0, "bendingStrength": 130.0, "bendingModulus": 3000.0, "impactStrength": null, "elongation": 40.0, "glassTransition": 159, "meltingPoint": 308, "hdt": 154, "drying": "Required", "desiccant": "Required", "nozzle": "320-400", "bed": "120-160", "speed": "<40", "fan": "0-25%", "enclosure": "Required"},
  {"name": "PEI (Ultem)", "family": "High performance", "summary": "Heat resistance, strength, cheaper other members of the PAEK family", "overview": null, "tensileStrength": 105.0, "tensileModulus": 3500.0, "bendingStrength": 130.0, "bendingModulus": 3000.0, "impactStrength": null, "elongation": 8.0, "glassTransition": 215, "meltingPoint": null, "hdt": 210, "drying": "Required", "desiccant": "Required", "nozzle": "360-400", "bed": "120-160", "speed": "<35", "fan": "0-25%", "enclosure": "Required"},
];
